### ISSUE TITLE
copyedit

### ISSUE THREAD

**Issue by rochelleterman** [rochelleterman/15-text_data#1]
Remove any time-specific phrases, like "in yesterday's class".

**Comment by GiacomoRamos** [comment]
1 - Preprocessing: a1d231cecb8cb7b75caaef02ee484e46c654e488
2 - Dictionary: 3c9f0138387a4a7798daa14de8b4156bb904f79b
3 - Distinctive: a16f95f818a132a2bf5fce1672cf99cba08fb60d

- In line 112, is it supposed to be the highest absolute difference or the highest proportional difference? @rochelleterman 

4 - STM: cfcbe034ecce1b026dc21dbcd87070c4984bbdf1
99 - Solutions: 06c85a958419c0c8442fa6f1099dbb91229be4f7

**Comment by rochelleterman** [comment]
It's highest absolute difference. Absolute here refers to absolute values, as in |x|.
